import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  const user = await prisma.user.upsert({
    where: { email: 'default@amazon-clone.dev' },
    update: {},
    create: { email: 'default@amazon-clone.dev', name: 'Default User' },
  })

  await prisma.cart.upsert({
    where: { userId: user.id },
    update: {},
    create: { userId: user.id },
  })

  const products = [
    {
      name: 'Echo Dot (5th Gen) Smart Speaker with Alexa',
      brand: 'Amazon',
      category: 'Electronics',
      description: 'Compact smart speaker with rich sound and Alexa. Control compatible smart home devices with your voice.',
      price: '4999.00',
      stock: 25,
      rating: 4.5,
      ratingCount: 12874,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1518444065439-e933c06ce9cd?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1512446733611-9099a758e4a2?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['Wi‑Fi + Bluetooth', 'Alexa built‑in', '1.73" speaker', 'Multi-room music'],
    },
    {
      name: 'Noise Cancelling Wireless Headphones',
      brand: 'SoundMax',
      category: 'Electronics',
      description: 'Over-ear wireless headphones with active noise cancellation and 30-hour battery life.',
      price: '7999.00',
      stock: 14,
      rating: 4.2,
      ratingCount: 5643,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1518441902117-f0a1b5949f3c?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1518444300222-5a1cc9dbba6a?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['ANC', '30h battery', 'Fast charge', 'Bluetooth 5.3'],
    },
    {
      name: 'Stainless Steel Water Bottle (1L)',
      brand: 'HydroPro',
      category: 'Home & Kitchen',
      description: 'Double-wall insulated bottle keeps drinks cold for 24h and hot for 12h.',
      price: '899.00',
      stock: 60,
      rating: 4.4,
      ratingCount: 23110,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1526401485004-2aa7d2c1aa6f?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1526402460708-36b58dfe4fe2?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['1L capacity', 'BPA-free', 'Vacuum insulated', 'Leakproof lid'],
    },
    {
      name: 'Non-stick Frying Pan (28cm)',
      brand: 'KitchenCraft',
      category: 'Home & Kitchen',
      description: 'Durable non-stick frying pan with even heating and ergonomic handle.',
      price: '1299.00',
      stock: 32,
      rating: 4.1,
      ratingCount: 9102,
      isPrime: false,
      images: [
        'https://images.unsplash.com/photo-1607330289024-1535c6b4e1f4?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1607346708144-1d5d295df1c1?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['28cm', 'PFOA-free', 'Induction compatible', 'Stay-cool handle'],
    },
    {
      name: 'Running Shoes for Men',
      brand: 'Stride',
      category: 'Fashion',
      description: 'Lightweight running shoes with breathable mesh and responsive cushioning.',
      price: '2999.00',
      stock: 18,
      rating: 4.0,
      ratingCount: 1422,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1528701800489-20be3c12f7df?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['Breathable mesh', 'Rubber outsole', 'Cushioned midsole', 'Everyday comfort'],
    },
    {
      name: 'Classic Cotton T‑Shirt',
      brand: 'Basics',
      category: 'Fashion',
      description: 'Soft cotton t‑shirt with a classic fit. Great for everyday wear.',
      price: '499.00',
      stock: 100,
      rating: 4.3,
      ratingCount: 8701,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1520975958221-09d4dcead8de?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1520975891868-2a1a2be2a91a?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['100% cotton', 'Classic fit', 'Machine washable', 'Breathable'],
    },
    {
      name: 'The Pragmatic Programmer (Paperback)',
      brand: 'Addison-Wesley',
      category: 'Books',
      description: 'A classic book with practical advice for software developers.',
      price: '699.00',
      stock: 45,
      rating: 4.8,
      ratingCount: 40221,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['Paperback', 'Programming', 'Best practices', 'Career growth'],
    },
    {
      name: 'Ergonomic Office Chair',
      brand: 'WorkWell',
      category: 'Furniture',
      description: 'Ergonomic chair with lumbar support and breathable back mesh.',
      price: '10999.00',
      stock: 8,
      rating: 4.1,
      ratingCount: 933,
      isPrime: false,
      images: [
        'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1505849879898-5b8dfd2b9d84?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['Lumbar support', 'Adjustable height', 'Breathable mesh', '360° swivel'],
    },
    {
      name: 'USB-C Charging Cable (2m)',
      brand: 'PowerLink',
      category: 'Electronics',
      description: 'Durable USB-C cable with fast charging support up to 100W.',
      price: '299.00',
      stock: 150,
      rating: 4.4,
      ratingCount: 15623,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1625948515291-69613efd103f?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['2m length', '100W support', 'Reinforced design', 'Nylon braided'],
    },
    {
      name: 'Yoga Mat (6mm)',
      brand: 'FitFlow',
      category: 'Sports',
      description: 'Premium yoga mat with excellent cushioning and non-slip surface.',
      price: '1599.00',
      stock: 35,
      rating: 4.6,
      ratingCount: 7842,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1539575909938-eb9e449b5d6d?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['6mm thickness', 'Non-slip', 'Eco-friendly', 'Lightweight'],
    },
    {
      name: 'Wireless Mouse Pro',
      brand: 'TechPro',
      category: 'Electronics',
      description: 'Precision wireless mouse with adjustable DPI and 18-month battery life.',
      price: '1299.00',
      stock: 42,
      rating: 4.3,
      ratingCount: 6521,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1610160203334-07a8df7e3c83?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['Wireless', 'Adjustable DPI', '18-month battery', 'Ergonomic design'],
    },
    {
      name: 'Smart Desk Lamp',
      brand: 'LightSmart',
      category: 'Electronics',
      description: 'LED desk lamp with adjustable brightness and color temperature.',
      price: '1899.00',
      stock: 28,
      rating: 4.5,
      ratingCount: 4321,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1565636192335-14c46fa1120b?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1572355174080-55f6a3f6e760?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['LED', 'Adjustable brightness', 'USB charging', 'Touch control'],
    },
    {
      name: 'Stainless Steel Lunch Box',
      brand: 'EcoMeal',
      category: 'Home & Kitchen',
      description: 'Eco-friendly stainless steel lunch box with 3 compartments.',
      price: '799.00',
      stock: 55,
      rating: 4.2,
      ratingCount: 3214,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1584765860541-3e7f17e0cbef?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1590973879405-2cf17d9c8ecf?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['3 compartments', 'BPA-free', 'Leakproof', 'Easy to clean'],
    },
    {
      name: 'Bluetooth Speaker Portable',
      brand: 'SoundBox',
      category: 'Electronics',
      description: '360° sound portable speaker with 12-hour battery and waterproof design.',
      price: '2499.00',
      stock: 22,
      rating: 4.7,
      ratingCount: 8932,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1589003077984-894e133814c9?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['360° sound', 'Waterproof', '12h battery', 'Portable'],
    },
    {
      name: 'Winter Jacket for Men',
      brand: 'WarmelyCo',
      category: 'Fashion',
      description: 'Insulated winter jacket with windproof and water-resistant exterior.',
      price: '3999.00',
      stock: 12,
      rating: 4.4,
      ratingCount: 2341,
      isPrime: false,
      images: [
        'https://images.unsplash.com/photo-1539668955282-d6b1b1c0d7c2?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1551186881-2d41b14a9e43?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['Insulated', 'Windproof', 'Water-resistant', 'Multiple pockets'],
    },
    {
      name: 'Leather Wallet RFID',
      brand: 'VerticalCraft',
      category: 'Accessories',
      description: 'Premium leather wallet with RFID protection for credit cards.',
      price: '899.00',
      stock: 78,
      rating: 4.5,
      ratingCount: 5623,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1515562141207-5dca89f118d5?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['RFID protection', 'Genuine leather', 'Multiple slots', 'Slim design'],
    },
    {
      name: 'Coffee Maker Drip',
      brand: 'BrewMaster',
      category: 'Home & Kitchen',
      description: 'Automatic drip coffee maker with programmable timer and carafe.',
      price: '1599.00',
      stock: 19,
      rating: 4.1,
      ratingCount: 3892,
      isPrime: false,
      images: [
        'https://images.unsplash.com/photo-1517668808822-9ebb02ae2a0e?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['12-cup carafe', 'Programmable', 'Keep-warm function', 'Auto-shutoff'],
    },
    {
      name: 'Phone Screen Protector',
      brand: 'ShieldTech',
      category: 'Electronics',
      description: 'Tempered glass screen protector with 9H hardness rating.',
      price: '349.00',
      stock: 200,
      rating: 4.2,
      ratingCount: 12341,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1592286927505-1def25e2c681?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['9H hardness', 'Tempered glass', 'Anti-fingerprint', 'Easy install'],
    },
    {
      name: 'Desk Organizer Set',
      brand: 'OfficeMax',
      category: 'Office',
      description: 'Complete desk organizer set with drawers and compartments.',
      price: '1299.00',
      stock: 33,
      rating: 4.3,
      ratingCount: 2134,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1631633633889-72960e2e1fef?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['Multiple drawers', 'Durable wood', 'Space-saving', 'Modern design'],
    },
    {
      name: 'Air Purifier HEPA Filter',
      brand: 'CleanAir',
      category: 'Home & Kitchen',
      description: 'HEPA air purifier removes 99.97% of airborne particles.',
      price: '4999.00',
      stock: 15,
      rating: 4.6,
      ratingCount: 4521,
      isPrime: false,
      images: [
        'https://images.unsplash.com/photo-1545530706-4e971eeb2b59?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1600126613408-eca07ce68773?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['HEPA filter', 'Covers 500 sqft', 'Quiet operation', 'Energy efficient'],
    },
    {
      name: 'Fast Charging Power Bank',
      brand: 'PowerCore',
      category: 'Electronics',
      description: '30000mAh power bank with USB-C and wireless charging.',
      price: '1999.00',
      stock: 37,
      rating: 4.5,
      ratingCount: 9876,
      isPrime: true,
      images: [
        'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1609107768506-24916e3a69e3?auto=format&fit=crop&w=900&q=80',
      ],
      specs: ['30000mAh', 'Fast charging', 'Wireless charging', 'USB-C'],
    },
  ]

  for (const p of products) {
    await prisma.product.upsert({
      where: { name: p.name },
      update: {
        brand: p.brand,
        category: p.category,
        description: p.description,
        price: p.price,
        stock: p.stock,
        rating: p.rating,
        ratingCount: p.ratingCount,
        isPrime: p.isPrime,
        images: p.images,
        specs: p.specs,
      },
      create: p,
    })
  }
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })

